name: 'Terraform CI/CD Pipeline'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform Action'
    defaults:
      run:
        shell: bash
        working-directory: Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURECRED }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: |
        terraform init -input=false \
          -backend-config="resource_group_name=${{ secrets.TF_RG }}" \
          -backend-config="storage_account_name=${{ secrets.TF_STORAGE }}" \
          -backend-config="container_name=${{ secrets.TF_CONTAINER }}" \
          -backend-config="key=${{ secrets.TF_KEY }}"
      env:
        ARM_CLIENT_ID: ${{ fromJson(secrets.AZURECRED).clientId }}
        ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURECRED).clientSecret }}
        ARM_TENANT_ID: ${{ fromJson(secrets.AZURECRED).tenantId }}
        ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURECRED).subscriptionId }}

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: |
        terraform plan -input=false \
          -var="vm_password=${{ secrets.TF_VM_PASSWORD }}" \
          -var="admin_username=${{ secrets.TF_ADMIN_USERNAME }}" \
          -var="myip=${{ secrets.TF_MY_IP }}"
      env:
        ARM_CLIENT_ID: ${{ fromJson(secrets.AZURECRED).clientId }}
        ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURECRED).clientSecret }}
        ARM_TENANT_ID: ${{ fromJson(secrets.AZURECRED).tenantId }}
        ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURECRED).subscriptionId }}

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        terraform apply -auto-approve -input=false \
          -var="vm_password=${{ secrets.TF_VM_PASSWORD }}" \
          -var="admin_username=${{ secrets.TF_ADMIN_USERNAME }}" \
          -var="myip=${{ secrets.TF_MY_IP }}"
      env:
        ARM_CLIENT_ID: ${{ fromJson(secrets.AZURECRED).clientId }}
        ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURECRED).clientSecret }}
        ARM_TENANT_ID: ${{ fromJson(secrets.AZURECRED).tenantId }}
        ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURECRED).subscriptionId }}